In [ ]:
import pandas as pd

Dataset: [https://www.kaggle.com/competitions/fake-news/data?select=train.csv](https://)

In [ ]:
df = pd.read_csv('/content/train.csv')

In [ ]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
df=df.dropna()

In [ ]:
X=df.drop('label',axis=1)
y=df['label']

In [ ]:
X.shape


(18285, 4)

In [ ]:
import tensorflow as tf
tf.__version__

'2.15.0'

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Bidirectional

In [ ]:
voc_size=5000

One Hot Representation


In [ ]:
messages=X.copy()

In [ ]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [ ]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[4975, 4630, 801, 2963, 1815, 6, 194, 27, 2461, 3310],
 [2542, 3140, 2938, 1819, 1618, 2228, 2613],
 [1454, 163, 4841, 2828],
 [1327, 1422, 3207, 1881, 2841, 4508],
 [2290, 1618, 2887, 4074, 4325, 455, 1618, 4784, 1315, 382],
 [1186,
  902,
  290,
  2612,
  4220,
  1981,
  3515,
  82,
  257,
  172,
  3263,
  4443,
  1673,
  162,
  2613],
 [2220, 423, 3137, 4567, 4594, 3481, 196, 2564, 4690, 2272, 1684],
 [3507, 1896, 73, 4362, 481, 2327, 1981, 3435, 4690, 2272, 1684],
 [1320, 2361, 3485, 313, 3174, 3135, 2906, 2865, 1981, 2243],
 [2100, 1889, 2414, 4535, 4493, 549, 1247, 3018],
 [3105, 4855, 927, 3386, 2330, 2178, 131, 3128, 3671, 1017, 267],
 [1881, 1880, 1815, 3135, 1981, 481],
 [469, 1007, 2631, 1286, 847, 3051, 4975, 3173, 1624],
 [1940, 2643, 1856, 2699, 4889, 153, 4584, 4690, 2272, 1684],
 [121, 2663, 500, 2970, 4456, 4690, 2272, 1684],
 [1401, 2946, 2769, 153, 1835, 703, 3250, 3338, 3170, 3768],
 [2928, 3694, 3140],
 [909, 3279, 3404, 475, 1981, 2823, 885, 2613],
 [1097, 2270, 

In [ ]:
#Embedding Representation
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...   27 2461 3310]
 [   0    0    0 ... 1618 2228 2613]
 [   0    0    0 ...  163 4841 2828]
 ...
 [   0    0    0 ... 4690 2272 1684]
 [   0    0    0 ... 2692 3551 3444]
 [   0    0    0 ... 3303 4716 1000]]


In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 4975,
       4630,  801, 2963, 1815,    6,  194,   27, 2461, 3310], dtype=int32)

In [ ]:
## creating Model LSTM
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [ ]:
len(embedded_docs),y.shape

(18285, (18285,))

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 19s 77ms/step - loss: 0.3264 - accuracy: 0.8476 - val_loss: 0.1926 - val_accuracy: 0.9167
Epoch 2/10
192/192 [==============================] - 15s 79ms/step - loss: 0.1393 - accuracy: 0.9447 - val_loss: 0.2133 - val_accuracy: 0.9109
Epoch 3/10
192/192 [==============================] - 14s 75ms/step - loss: 0.0994 - accuracy: 0.9628 - val_loss: 0.2252 - val_accuracy: 0.9157
Epoch 4/10
192/192 [==============================] - 14s 75ms/step - loss: 0.0703 - accuracy: 0.9758 - val_loss: 0.2469 - val_accuracy: 0.9138
Epoch 5/10
192/192 [==============================] - 12s 60ms/step - loss: 0.0526 - accuracy: 0.9808 - val_loss: 0.3369 - val_accuracy: 0.9122
Epoch 6/10
192/192 [==============================] - 11s 59ms/step - loss: 0.0339 - accuracy: 0.9896 - val_loss: 0.3719 - val_accuracy: 0.9085
Epoch 7/10
192/192 [==============================] - 12s 64ms/step - loss: 0.0246 - accuracy: 0.9922 - val_loss: 0.4123 - val_accuracy:

In [ ]:
#adding dropouts

from tensorflow.keras.layers import Dropout
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
#performance metrics and accuracy
#performance metrics and accuracy
y_pred_probs = model.predict(X_test)  # Get predicted probabilities
y_pred = (y_pred_probs > 0.5).astype(int)  # Convert probabilities to class labels (0 or 1)

189/189 [==============================] - 3s 9ms/step


In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred)

array([[3014,  405],
       [2364,  252]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5411764705882353

In [ ]:
#creating model using bidirectional LSTM
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_6 (Embedding)     (None, 20, 40)            200000    
                                                                 
 bidirectional_2 (Bidirecti  (None, 200)               112800    
 onal)                                                           
                                                                 
 dropout_5 (Dropout)         (None, 200)               0         
                                                                 
 dense_4 (Dense)             (None, 1)                 201       
                                                                 
Total params: 313001 (1.19 MB)
Trainable params: 313001 (1.19 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [ ]:
len(embedded_docs),y.shape

(18285, (18285,))

In [ ]:
import numpy as np
X1_final=np.array(embedded_docs)
y1_final=np.array(y)

In [ ]:
X1_final.shape,y1_final.shape


((18285, 20), (18285,))

In [ ]:
from sklearn.model_selection import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(X1_final,y1_final, test_size=0.33, random_state=42)

Model Training

In [ ]:
model1.fit(X1_train,y1_train,validation_data=(X1_test,y1_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 32s 139ms/step - loss: 0.2947 - accuracy: 0.8616 - val_loss: 0.1978 - val_accuracy: 0.9188
Epoch 2/10
192/192 [==============================] - 23s 122ms/step - loss: 0.1404 - accuracy: 0.9464 - val_loss: 0.2022 - val_accuracy: 0.9171
Epoch 3/10
192/192 [==============================] - 23s 120ms/step - loss: 0.0892 - accuracy: 0.9691 - val_loss: 0.2541 - val_accuracy: 0.9143
Epoch 4/10
192/192 [==============================] - 16s 83ms/step - loss: 0.0553 - accuracy: 0.9806 - val_loss: 0.2915 - val_accuracy: 0.9109
Epoch 5/10
192/192 [==============================] - 14s 75ms/step - loss: 0.0378 - accuracy: 0.9872 - val_loss: 0.3368 - val_accuracy: 0.9087
Epoch 6/10
192/192 [==============================] - 15s 79ms/step - loss: 0.0242 - accuracy: 0.9921 - val_loss: 0.4585 - val_accuracy: 0.9082
Epoch 7/10
192/192 [==============================] - 15s 79ms/step - loss: 0.0218 - accuracy: 0.9932 - val_loss: 0.4192 - val_accura

In [ ]:
y_pred_probs1 = model.predict(X1_test)  # Get predicted probabilities
y_pred1 = (y_pred_probs1 > 0.5).astype(int)  # Convert probabilities to class labels (0 or 1)

189/189 [==============================] - 3s 16ms/step


In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y1_test,y_pred1)

array([[3014,  405],
       [2364,  252]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y1_test,y_pred1)

0.5411764705882353

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y1_test,y_pred1))

              precision    recall  f1-score   support

           0       0.56      0.88      0.69      3419
           1       0.38      0.10      0.15      2616

    accuracy                           0.54      6035
   macro avg       0.47      0.49      0.42      6035
weighted avg       0.48      0.54      0.45      6035

